version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: AE.Http.Proxy.sln
  parallel: true
  verbosity: minimal